### PR TITLE
Pin dependencies

### PR DESCRIPTION
**Pull request by k-dominik**
see discussion here: https://github.com/ilastik/ilastik-publish-packages/pull/15

Todos:
 * [x] reset build number (remove from yaml maybe)
 * [x] make it a `noarch` package, remove related variables from build string

### CODE REVIEW

**Comment by stuarteberg** [comment]
Some comments:

1. There is no need to bump the build number here, because this recipe lives inside the `wsdt` repo itself, and the version includes `.post{{GIT_DESCRIBE_NUMBER}}`.  The build number is only necessary when differentiating between two builds with identical versions.  In cases like this, it is impossible to end up with two builds that have identical versions.

2. This package is pure-python, and thus does not rely on the numpy ABI.  Therefore, there is no need to include `{{CONDA_NPY}}` in the build string.

      - Related: Hopefully the numpy version is not getting pinned too closely in the package `run` requirements. I see there is no constraint for the `numpy` version specified in the recipe, but I admit I'm a little unsure of what magic `conda-build` might apply here.  We should inspect the resulting package to be sure, and adjust the `run` requirement if necessary.

3. (Unrelated to this PR) As far as I can tell, this package should be `noarch: python`, right?  I'm not sure why I didn't write it that way from the beginning.

**Comment by k-dominik** [comment]
Thank you very much @stuarteberg . I'll take care of your suggestions

> Related: Hopefully the numpy version is not getting pinned too closely in the package run requirements. I see there is no constraint for the numpy version specified in the recipe, but I admit I'm a little unsure of what magic conda-build might apply here. We should inspect the resulting package to be sure, and adjust the run requirement if necessary.

I'll have linux packages for the current version on the [kdominik anaconda channel](https://anaconda.org/kdominik/). With the current configuration, conda pins numpy to `x.x`:
```
    numpy >=1.12,<1.13.0a0
    python >=3.6,<3.7.0a0
    vigra >=1.11
```

Furthermore, I think it makes sense to pin numpy (because of changes in their api) at least to the minor versions also for pure python packages that just use numpy from python.

**Comment by stuarteberg** [comment]
Thanks for the info.  Makes sense.

**Comment by k-dominik** [comment]
well okay, I went `noarch` with this package, but it still feels a bit strange:

* `python` version is constrained to be `>=2.7`, this is in accordance to the "old" `meta.yaml`
* version of `numpy` is pinned, as its python api might change.
  I guess the clean way would be to test it with all versions of `numpy` available and then just adjust the constraint there accordingly, or do you know of a better way @stuarteberg?
  For the time being, i kept the `numpy` version used/tested in the build string, as we might relax requirements imposed on `numpy` when we upgrade it and are confident that it works with a certain
  version without changing any python code, but with an external variant config file.
  Say we currently only build it with `1.12`. Once we switch to `1.14` we could find that it works well right out of the box - no changes needed. In this case we just want to build it a different version pinning which might come  from an external config file `ilastik-pins.yaml` -> commit hash is unchanged but we can at least be sure that it works with the newly pinned version.

**Comment by stuarteberg** [comment]
>`python` version is constrained to be `>=2.7`

I think that should be fine, right?  Am I missing something?

>version of numpy is pinned, as its python api might change.

Everything you say is reasonable.  In my own packages, I rarely worry about breaking changes in future versions of the numpy python API, but it is theoretically possible, as you point out.  Since you're maintaining a huge set of recipes, I understand the preference to play it safe.

>I guess the clean way would be to test it with all versions of numpy available and then just adjust the constraint there accordingly, or do you know of a better way

No, I don't, other than carefully examining the change notes and then considering whether or not they include changes that would break this package.  But that sounds much harder than running the tests!  (I think the tests in this package have reasonable coverage, FWIW.)

**Comment by k-dominik** [comment]
Thank you very much for the quick and helpful feedback @stuarteberg :)

sorry I don't think I was thinking straight, when I wrote the bit about `python >=2.7`. Of course that is perfectly fine

**Pull request merged**
